### ISSUE TITLE
Improvement: Add Next Text (Link) After Conclusion

### ISSUE THREAD

**Issue by petprog** [Yczar/test-driven-dart#8]
Add a next text that link a page to the next page.
For instance, I am on Page_1.md want to go to Page_2.md
```
[Next](Page_2.md)
```
You may add it after Conclusion.

**Comment by Yczar** [comment]
@jjboy55

**Comment by jeremiah-louis** [comment]
for each section ?

**Comment by petprog** [comment]
For each page that has a next page

**Comment by jeremiah-louis** [comment]
alright

**Comment by Yczar** [comment]
I think this is sorted already @petprog 

I will be closing this now!
